### ISSUE TITLE
After updating the splash in 3.16 it is not visible anymore

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/projecta#1216]
I thought to update the splash with the upcoming one from Google drive of Anita,
but after editing (the version) it is not visible anymore in the site:
https://changelog.qgis.org/en/qgis/version/3.16/
https://changelog.qgis.org/media/images/projects/dbc0cef663f2f652e0961ac2ed168eb45ed2e182.png gives an 'forbidden'..

**Comment by zacharlie** [comment]
I have had this issue with media on the changelog. Sometimes (although not always) uploading the image again resolves it... Still an issue that needs to be resolved but the "turn it on and off again" routine seems to be a possible workaround.

**Comment by rduivenvoorde** [comment]
Just tried to upload it again, it is current splash:
https://drive.google.com/open?id=1GmSpwppbX9dIjYrf3n_ZelC97Bv-lRYU

But it still does not show up:

![Screenshot-20201006120201-1348x445](https://user-images.githubusercontent.com/731673/95187708-c2a0b680-07cb-11eb-8b99-a8ddd94d8cb6.png)

url is now: https://changelog.qgis.org/media/images/projects/dbc0cef663f2f652e0961ac2ed168eb45ed2e182.png

**Comment by zacharlie** [comment]
I see. I tried as well and when it redirected to the versions list I see the thumbnail is available... bu I also get a permissions error (403) when trying to access the actual file. Might be a webserver config issue... Or a user permissions problem...

![image](https://user-images.githubusercontent.com/64078329/95191070-83289900-07d0-11eb-8525-9e63f450bbdf.png)

**Comment by timlinux** [comment]
So it is a bug in that if you change the splash or version text, the version gets unpublished. @sumandari can you make sure the publish status remains intact after doing any edits?

**Comment by rduivenvoorde** [comment]
@timlinux what do you mean 'get unpublished'? I do not think 3.16 got unpublished, did it?

https://changelog.qgis.org/en/qgis/version/3.16/

Just the permissions of the image file seem wrong?
As @zacharlie says (and shows in the screenie above), 3.16 is in the Versions list, AND shows the right splash (there!)...
I think @zacharlie ment to say that he get's a permission error when he tests the image url

**Comment by timlinux** [comment]
Ok I fixed the image. @sumandari the bug is actually if you save the version description in the frontend editor, it drops the release date. If you save it in django admin, it preserves the date.

So: 

https://changelog.qgis.org/en/site-admin/changes/version/53/change/ works
https://changelog.qgis.org/en/qgis/version/3.16/update/ drops publish date on save.


@rduivenvoorde sorry I got my wires crossed and was thinking of another issue.

@rduivenvoorde btw when a version has no date, it has no sponsors listed, so if you are testing the importer you can try again now and should see a full list of sponsors.

**Comment by rduivenvoorde** [comment]
@timlinux thanks!

Yes I was testing the import. But will wait for https://github.com/kartoza/prj.app/issues/1217 to be fixed, to test again, otherwise I have to fix the rst manually first on a lot of lines....

**Comment by sumandari** [comment]
@timlinux 

> https://changelog.qgis.org/en/qgis/version/3.16/update/ drops publish date on save.

As per your description, the bug is spot on.  I found out that the VersionForm needs to assign the value of release_date attribute when the instance invoking save method, since it doesn't include the release_date in the form Fieldset.

I added these 3 lines after  [https://github.com/kartoza/prj.app/blob/develop/django_project/changes/forms.py#L98](https://github.com/kartoza/prj.app/blob/develop/django_project/changes/forms.py#L98) and tested it on my localmachine, it preserved the release_date:
   ```
 def save(self, commit=True):
        ...
        version = Version.objects.get(pk=instance.pk)
        if version:
            instance.release_date = version.release_date
        ...
        return instance
```

**Comment by rduivenvoorde** [comment]
@timlinux @sumandari is this deployed automagically? I'm just wondering when it will show up in the real site (feel more or less responsible for this breakage....) :-)

**Comment by sumandari** [comment]
@rduivenvoorde 
Sorry I just moved this issue from **in progress** to **done** so that make this issue closed :sweat_smile:. I reopen this issue and  will ask @timlinux to confirm about the deployment.
