### ISSUE TITLE
Ensure that logins redirect to the correct location

### ISSUE THREAD

**Issue by zacharlie** [kartoza/projecta#1258]
It has been reported that some users are redirected to the wrong site (e.g. from changelog.kartoza.com to changelog.qgis.org) after logging in with some Auth providers (e.g. GitHub). Users should always be redirected to the correct landing page after logging in.

**Comment by sumandari** [comment]
Hi @zacharlie, I have experienced it too. When I log into changelog.qgis.org with GitHub account it will redirect to correct site. But if I was at changelog.kartoza.com it will redirect to changelog.qgis.org after logged in. 

@timlinux could you please advise if the GitHub Authorization callback URL will redirect user to changelog.kartoza.com instead of changelog.qgis.org? Thank you.

**Comment by timlinux** [comment]
Hi.I mentioned this to you too .it should not take you to a different site.

**Comment by sumandari** [comment]
Well noted. @timlinux could you please confirm if `Secret key` in table socialaccount_socialapp was generated for redirecting to changelog.kartoza.com?

**Comment by sumandari** [comment]
The fix #1269 has been deployed on staging server

**Comment by sumandari** [comment]
The fix #1262 has been deployed.
