### ISSUE TITLE
Generated rst image issue 2

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/projecta#1305]
Some (not all) images have a path like:
"/mediaimages/entries/14df1b85a3e3ada3024a39499a245bbdd7e2ca64-1.png"

giving the build error:

/QGIS-Website/source/site/forusers/visualchangelog318/index.rst:808:image file not readable: mediaimages/entries/14df1b85a3e3ada3024a39499a245bbdd7e2ca64-1.png

I can easily fix it by just replacing "/mediaimages" with "images' because apparently the images ARE there, only the path is not created OK.

Seems fixable

**Comment by timlinux** [comment]
Thanks @rduivenvoorde @sumandari will you take a look please? The incoming issues from @rduivenvoorde are time critcal as we need to get the release announcements out on time.

**Comment by sumandari** [comment]
@rduivenvoorde @timlinux 

I think the image came from fetching github which had issue in https://github.com/kartoza/prj.app/issues/1282.
It generated an incorrect path
```
/media/media/images/entries/14df1b85a3e3ada3024a39499a245bbdd7e2ca64-1.png
```

This issue has been fixed by https://github.com/kartoza/prj.app/pull/1284 and deployed yesterday.

![image](https://user-images.githubusercontent.com/40058076/108445186-e48c6880-7296-11eb-8d53-7b5132f12000.png)


This incorrect path will lead the another issue in download version.
https://github.com/kartoza/prj.app/blob/ede5c2f32a78083a86e5cb0f60c1a2ac3bc4b443/django_project/changes/views/version.py#L567
that will replace the url to 
```
'/mediaimages/entries/14df1b85a3e3ada3024a39499a245bbdd7e2ca64-1.png'
```
the one that you mentioned.

**Comment by sumandari** [comment]
I will try to fix the url value in the database with custom management command.

**Comment by sumandari** [comment]
@rduivenvoorde @timlinux 

The fix has been deployed. 
The image in our sample case `images/entries/14df1b85a3e3ada3024a39499a245bbdd7e2ca64-1.png` is displayed on the page now.

/cc @dimasciput 

![image](https://user-images.githubusercontent.com/40058076/108507687-a4a89e00-72f5-11eb-80c4-1a88757e59a8.png)

**Comment by rduivenvoorde** [comment]
@sumandari This is also working/fixed now. Thanks!
