### ISSUE TITLE
Certificate preview generation fails

### ISSUE THREAD

**Issue by spatialthoughts** [kartoza/projecta#1313]
When trying to preview a certificate for a course, I get an error "Error:Failed to load PDF document."

URL for the error
https://changelog.qgis.org/en/qgis/certifyingorganisation/spatial-thoughts/preview-certificate/

**Comment by sumandari** [comment]
Hi @spatialthoughts.

The link you mentioned will return this following image instead of "Error:Failed to load PDF document.".
Could you please confirm if the error of this issue is still same?

![image](https://user-images.githubusercontent.com/40058076/108990891-63880380-76d2-11eb-86ef-eb7b43ac16fd.png)

**Comment by spatialthoughts** [comment]
Thanks. Seems to work fine now. Closing the issue.
