### ISSUE TITLE
[Certification] Error creating a new course

### ISSUE THREAD

**Issue by geomenke** [kartoza/projecta#1357]
I have been trying to create a new course under Septima's certification page and I get this error 500:

> 500
Ooops. Something broke....

>The powers that be have been informed.
In the meantime, please form an orderly queue and head to the home page.

>If you need assistance, you may reference this error as 77ea4aea60af42e087c4ac16108477f1.

I created a course here successfully this spring so I am not sure what is causing this.

**Comment by sumandari** [comment]
Thank you for your report @geomenke. I will look into this.

**Comment by sumandari** [comment]
Hi @geomenke,

My apologies for the delay. From the log error, the course name you tried to create will create a slug `introduction-gis-with-qgis` that has already been used by another organization.
The fastest way to recreate is, rename your course so that it will give another slug, then edit and change the course name as it should be.

Now I am working on the fix. I will inform you once the fix has been done and deployed.

**Comment by geomenke** [comment]
I would think this would have come up a lot with course names like `Introduction to QGIS`.  Thanks for addressing it.

**Comment by sumandari** [comment]
Hi @geomenke the fix has been deployed in version 2.2.0

**Comment by geomenke** [comment]
@sumandari thanks. It is working well for me.

**Comment by sumandari** [comment]
Great!
Thank you @geomenke. I will close the ticket for now.
