### ISSUE TITLE
We need to support invoice generation for sponsors

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#235]
From @andreasneumann 

> Could we add a function to generate a sponsorship invoice?

**Comment by andreasneumann** [comment]
I'll send an invoice example by mail. Contains confidential data - so it shouldn't be publically on github.

I can prepare a "neutral" example though.

**Comment by timlinux** [comment]
We can use something like this to do the report generation

https://github.com/simonluijk/django-invoice

**Comment by andreasneumann** [comment]
Hi Tim,
https://docs.google.com/document/d/1RMujVZ8tXEHzKYjrXVQbxqE34M9VTyuwCGqntsmJdww/edit is a template. Feel free to adapt. Content in [ ] should be replaced by dynamic content. In case of address, since this is quite different from country to country, I would agree, we could have a free-form address like you already implemented it in Projecta last weekend.

**Comment by timlinux** [comment]
See #272
