### ISSUE TITLE
We need a 'Manage menu'

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#255]
It should appear next to the Project menu (before add) and have:

* Versions
* Categories
* Sponsors
* Sponsorship Levels
* Sponsorship Periods
* Committees
* Votes

**Comment by rischanlab** [comment]
Hi @timlinux about the votes and committees the reason why those are not showing up is because we don't have any data inside the tables. 

![screen shot 2016-03-08 at 1 51 33 pm](https://cloud.githubusercontent.com/assets/2235894/13594211/ff210632-e534-11e5-8f77-bbfd6d4014f3.png)

now I am looking for the last backup data for the votes and committess

**Comment by rischanlab** [comment]
Hi @timlinux for the menus view, do you mean like this Tim? 

![screen shot 2016-03-15 at 1 19 14 pm](https://cloud.githubusercontent.com/assets/2235894/13769237/ae9256ea-eab0-11e5-95c4-c511c427fc84.png)

I need your response before I push my PR. 

Thanks

**Comment by timlinux** [comment]
I think it looks good @rischanlab 
Maybe another refinement would be to do a single menu for version related things so

**Changelogs**
Manage Versions
Manage Categories

**Sponsors**
Manage Sponsors
Manage Levels 
Manage Periods

I'd also like to get rid of the add menu and have all the add done using the little ``*`` buttons on the relevant view.

**Comment by rischanlab** [comment]
Fixed by https://github.com/kartoza/projecta/pull/280
