### ISSUE TITLE
Feature: Training Center Register & Print Certificate

### ISSUE THREAD

**Issue by ann26** [kartoza/projecta#392]
Please feel free to comments and share your thoughts.
Below is the descriptions and layout of the new feature.

This new feature has 2 functions, including to register as a new Training Centre and to issue certificate for students who have completed their training. The flowchart is shown as follows:
![flowchart simplified](https://cloud.githubusercontent.com/assets/26101337/23781927/214e4cfa-0583-11e7-920f-5f750c402ec1.png)

The feature layout is shown below. 
![layout_simplified](https://cloud.githubusercontent.com/assets/26101337/23781902/e8c66836-0582-11e7-91b5-c72511c6fe1b.png)

When a user is registering as a new Training Centre, user will need to fill out the information to the register form shown below. Once submitted, the user will receive notification that the information is being verified by Kartoza member. Here, Kartoza member will be notified.
![training centre register](https://cloud.githubusercontent.com/assets/26101337/23760605/d45aaf48-0522-11e7-952b-e1352025cebf.png)
The blue word “page” will contain a link to Kartoza page.

As for a student, when a student wants to print his/her certificate of completion, the student needs to fill out information form as shown below.
![print certificate](https://cloud.githubusercontent.com/assets/26101337/23760621/e2b0331a-0522-11e7-9e4f-0747f105e5d4.png)

After submitting, the student should pay a fee before proceed to printing section. 
![payment](https://cloud.githubusercontent.com/assets/26101337/23760628/e70b1a7e-0522-11e7-9f42-042b0c4e3f08.png)

After submitting the payment information, it will generate a pdf file of the certificate as shown below. 
![certificateqgisemcbethfeb17](https://cloud.githubusercontent.com/assets/26101337/23759871/9514b9de-0520-11e7-94b6-c8e6a9b88bc6.png)

**Comment by timlinux** [comment]
Thanks for this @ann26 cc @geomenke @foss4geo

![certificationschema](https://cloud.githubusercontent.com/assets/178003/23827461/9ed40fae-06bc-11e7-93fb-d6b67c7a1f64.png)


The above is a proposed ER diagram for the new certification platform. Here are some notes to accompany this diagram:

* Each project (which is already a model in projecta) can have zero or more **Certifying Organizations**. Certifying Organizations should be approved by a project administrator (need to check if we already have a role for this)
* Each Certifying Organisation can have zero or more **Course Conveners**. A course mentor has a user id that links them to a user in the Projecta auth app.
* Each Certifying Organisation can have zero or more **Course Types**. A course type should have a name, description, number of instruction hours, link to web site for the course type  e.g. "Beginner QGIS Course" and "Detailed description about Beginner QGIS Course", 40 hours, http://foo.com/qgis-beginner course.
* Each Certifying Organisation can have one or more **Courses**. Each course should also have a related course type and course convener as properties as well as the date start and date end for the course and a notes field.
* The **Course Attendees** model should  be used to relate an attendees to a course.
* The **Attendee** model should have a name, surname and email field. The attendees does **not** need to be a user on the Projecta auth model and there is no need for them to register on the site.
* The Course Convener will issue a Course Attendee with a **Certificate** by referencing the Course and Attendee. When the Certificate record is created, a unique number will be created for the project certificate. This number should be sequential and project specific. For example QGIS-1, QGIS-2, InaSAFE-1 etc. 
 * The certificate shall not be issued until the certificate has been paid for. 
 * The payment does not require a log in and can either be made by the course convener or by the course attendee. 
 * Once the payment has been made a PDF certificate will be generated similar to the one in your spec above. Note that elements in the certificate should be rendered according to the active project and course details.
 * An additional view should allow any third party to enter a unique  course certificate number and view the certificate. This view should include a watermark over the certificate indicating that it is a verification copy. The purpose of this view is so that third parties can verify that a given person is indeed a successful course alumni.

**Comment by ann26** [comment]
Thank you @timlinux , I will work on it.

![erdplus-diagram](https://cloud.githubusercontent.com/assets/26101337/23840626/570b1a6e-07d9-11e7-9189-ed568c0f180e.png)
Above is the proposed ER diagram for the training centre registration platform. The descriptions are as follows:

- An organisation/user may register as a new **training centre** and should be approved by projecta admin / Kartoza member. Hence, there will be a notification to admin when a user register a new training centre. 
- When a registration is approved, the user will be notified.
- Each training centre may hold one or more **course(s)**.

Just to be sure, the course conveners which are mentioned in the proposed ER diagram for the new certification platform is the same as training centre, isn't it?

**Comment by timlinux** [comment]
Hi. No

You have a training center / organisation that runs one or more courses. Each course has one or more trainers / conveners that are qualified to run the course.

![courseconveners](https://cloud.githubusercontent.com/assets/178003/23844393/873044f8-07ca-11e7-9607-1cf21f5d02ea.png)

**Comment by ann26** [comment]
I understand now, thank you!

So, when a training centre / organisation register to run a course, should they also register the course trainer? or will Kartoza provide the trainer? or could it be both?

**Comment by timlinux** [comment]
@ann26 

> So, when a training centre / organisation register to run a course, should they also register the course trainer? or will Kartoza provide the trainer? or could it be both?

So firstly you should not think specifically about kartoza - we are building a generic tool so any organisation could register as a training provider.

The workflow is:

1)  A project administrator (e.g. in the QGIS project) creates a new training organisation and adds one or more Projecta users to function as administrators to that project.
2) Project administrators create course conveners by assigning one or more Projecta users to act as course conveners for a course.

**Comment by timlinux** [comment]
@ann26 Note that I updated my comments above with a new version of the diagram and a bullet item about training centers.

**Comment by ann26** [comment]
Ah alright @timlinux , I will amend the code

**Comment by ann26** [comment]
![layout_updated](https://cloud.githubusercontent.com/assets/26101337/24183375/8b47f14e-0efa-11e7-9946-c9100beb687a.png)

Above is updated menu layout since the last one didn't include certifying organisation.

**Comment by cchristelis** [comment]
@timlinux and @ann26, could we please have a better name than CourseAttendee. I mean this word does not communicate the intent, which is more to the effect of a course instance.

**Comment by timlinux** [comment]
Note that the example pdf for the certificate above will not look like that - it should include a separate logo for the course presenter and the project logo and be project branded.
