### ISSUE TITLE
add certification system explaination

### ISSUE THREAD

**Issue by mbernasocchi** [kartoza/projecta#727]
We should have a text explaining how the certification system works and that the certification fees go directly to the QGIS project.

**Comment by timlinux** [comment]
@mbernasocchi have you seen this icon (the one with the tooltip showing)?

![screen shot 2018-02-01 at 23 58 39](https://user-images.githubusercontent.com/178003/35705707-e6844e72-07ab-11e8-9bc1-4259dce85c77.png)


Click it and you will get a page full of details about how the certification system works. I'm trying to keep the text generic since everything we are building here can be used by any project. Maybe I will add something in project properties in future that can provide custom text in the help, but its not on my plan for right now. If you want to suggest an improvement to the current text I will welcome it....

**Comment by mbernasocchi** [comment]
![image](https://user-images.githubusercontent.com/233663/35722362-4510c6c4-07f6-11e8-9121-8740306ee52b.png)

beside the fact that I didn't see it (it is really not prominent enough) I can't click it since it is greyed out

**Comment by mbernasocchi** [comment]
the main issue I see, is to convey clearly the idea that by issuing a certificate, the certification organization supports the QGIS project and does not make 20 extra €.

**Comment by timlinux** [comment]
If we want to convey that clearly it should go on the certificate itself and / or on the certificate validation page. Something like:

"By receiving this certificate, XXX Euros has been donated to YYY Project"

If there is no cost for the certificate (e.g. InaSAFE) then the message should not be shown.
